### ISSUE TITLE
Use language server to replace its completion?

### ISSUE THREAD

**Issue by Freed-Wu** [liuchengxu/graphviz.vim#12]
There is a [language server](https://github.com/nikeee/dot-language-server) for dot. Can we remove the completion function and let user to use language server, just keep compile function (LSP doesn't have this feature)?

- For developers, it can save maintain cost.
- For users, language server can provide better experience.

**Comment by Freed-Wu** [comment]
Hey, what is your opinion? If you agree, I think I can do it :smile: And if you are busy, you can add me to collaborator :+1:

**Comment by liuchengxu** [comment]
Collaborator invite sent.

I don't think the existing completion function has to be removed, you can keep it as is and extend it with the language server support, for the language server is not always available.

**Comment by Freed-Wu** [comment]
Perhaps we can disable completion when `executable('dot-language-server') == v:true` because two same completions will give user confusion?

**Comment by liuchengxu** [comment]
By default only the omnifunc is defined, can you elaborate on how it interferes with the completion from the language server? I guess they can just co-exist as these two completions have different triggers.

https://github.com/liuchengxu/graphviz.vim/blob/dbe1de334097891186e09e5616671091d89011d5/ftplugin/dot.vim#L6

**Comment by Freed-Wu** [comment]
Oh, let me rethink if there are any method to combine LSP with this plugin.
