### ISSUE TITLE
feature request: allow args to be passed to viewer

### ISSUE THREAD

**Issue by windowsrefund** [liuchengxu/graphviz.vim#7]
Thanks for this excellent plugin. I thought I'd be able to set g:graphviz_viewer = 'open -g' in order to bypass the undesirable side effect of open grabbing focus. This doesn't seem to be possible so I'm wondering if it would be possible to introduce something along the lines of a g:graphviz_viewer_args

**Comment by Freed-Wu** [comment]
> This doesn't seem to be possible

Now you can.
