### ISSUE TITLE
Not working in nvim 

### ISSUE THREAD

**Issue by 71GA** [liuchengxu/graphviz.vim#8]
I created a folder, mooved inside and cloned the repository:
`
mkdir -p ~/.config/nvim/pack/graphviz/start
cd ~/.config/nvim/pack/graphviz/start
git clone https://github.com/liuchengxu/graphviz.vim
`
Built in plugin manager should find the plugin, but when I open Nvim and try to enter `:Graphviz`, it can't find the command:
`
Not an editor command: Graphviz`

**Comment by 71GA** [comment]
I found out that folder `ftplugin` has to be renamed to `plugin` in order for native plugin manager to detect it. Folder names are NOT to be freely chosen like developer did it. I suggest renaming folders according to vim/nvim convention...

**Comment by liuchengxu** [comment]
That's intentional as vim/neovim won't load this plugin until you open a .gv/.dot file.

**Comment by 71GA** [comment]
Okay! It was not mentioned in the documentation. Maybe add this not as I thought plugin might not work.

**Comment by liuchengxu** [comment]
README updated.
